version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: dev-gmb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql@17/data/pgdata
      POSTGRES_INITDB_ARGS: '--encoding=UTF8 --lc-collate=C'
    ports:
      - '0.0.0.0:5432:5432'
    volumes:
      - /data:/var/lib/postgresql/data
    command: ['postgres', '-c', 'log_statement=all', '-c', 'listen_addresses=*']
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    depends_on:
      - db
