# fly.toml app configuration file generated for guildmanagementbot on 2023-11-01T09:51:51Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "devgmb"
primary_region = "lhr"

[build]

[[mounts]]
  source = "bot_data"
  destination = "/data"
