# fly.toml file generated for guildmanagementbot on 2023-04-16T15:48:28+01:00

app = "guildmanagementbot"
primary_region = "lhr"

[deploy]
  release_command = "npm run migrate"

[mounts]
  source="bot_data"
  destination="/mnt/bot_data"